---
title: "The office tidytuesday"
output: html_notebook
---

```{r}
library(tidyverse)
library(schrute)
library(ggraph)
library(tidygraph)
library(ggtext)

```


```{r}
office_ratings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-03-17/office_ratings.csv')
transcripts <- schrute::theoffice
```

```{r}
laugh <- transcripts %>% 
  mutate(direction = str_extract(text_w_direction,"(?<=\\[).+?(?=\\])"),
   laughts = str_detect(direction,"laugh"),
    previous_character = lag(character,1),
    previous_conversation = lag(text,1)) %>% 
  filter(laughts == TRUE)
```

```{r}
laugh %>% group_by(as.numeric(season)) %>% summarize(n = n())
laugh %>% group_by(character) %>% summarize(n = n()) %>% arrange(desc(n))
laugh %>% group_by(previous_character) %>% summarize(n = n()) %>% arrange(desc(n))
```
Get characters that laugh or make laugh other the most, filter > 5
```{r}
limit <- 5
laugh_most <- laugh %>% 
  group_by(character) %>% 
  summarize(n = n()) %>% 
  filter(n > limit) %>% 
  pull(character)
make_laugh_most <- laugh %>% 
  group_by(previous_character) %>% 
  summarize(n = n()) %>% 
  filter(n > limit) %>% 
  pull(previous_character)
showcase_characters <- c(laugh_most,make_laugh_most) %>% unique()

laugh_graph <- laugh %>% 
  mutate(character_edit = ifelse(character %in% showcase_characters,character,"Others"),
    previous_character_edit = ifelse(previous_character %in% showcase_characters,previous_character,"Others")) %>% 
  group_by(character_edit,previous_character_edit) %>% 
  summarize(n = n()) %>% 
  arrange(desc(n)) %>% 
  as_tbl_graph() 

special_characters <- c("Pam","Michael","Dwight","Jim","Andy","Others")


ggraph(laugh_graph,layout = "graphopt") + 
  geom_edge_parallel(aes(alpha = n,
    start_cap = label_rect(node1.name),
                     end_cap = label_rect(node2.name)),
    color =  "#54e0f1",
    show.legend = FALSE,
                 arrow = arrow(length = unit(2, 'mm')),
    width = 0.5) + 
   geom_edge_loop(colour = "#cccccc") +
  geom_node_text(aes(label = name,color = ifelse(name %in% special_characters,"#222222","#6d6d6d")),
    show.legend = FALSE) +
   theme_minimal() +
  theme(legend.position = "bottom",
    plot.title = element_text(size = 20, hjust = 0.5),
    plot.subtitle = element_text(size = 12, hjust = 0.5, vjust = 1,lineheight = 0.5),
    strip.text = element_text(size = 10, face = "bold"),
    plot.caption = element_text(size = 7.5),
    axis.title = element_text(size = 12),
    legend.title = element_text(size = 10),
    legend.text =  element_text(size = 7.5),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    #legend.text.align = 0,
    panel.grid = element_blank(), 
    panel.background = element_blank()) +
  labs(title = "LMAO: The Office version",
    subtitle = "Who laughs the most in The Office (US), and who is making them laugh.\n 
    Based on the direction comments and who is the previous character talking.",
    x = "",
    y = "",
    alpha = "Laughts generated by each characted to who",
    caption = "Data: schrute package \n@perspectivalean")

ggsave("output/the office github.png",plot = last_plot(),width = 31.75/1.5,height = 17.85/1.5,units = c("cm"),dpi = 600)
```



